# Nixpacks configuration for Railway deployment

[phases.setup]
nixPkgs = ["python311", "gcc"]

[phases.install]
cmds = ["pip install --upgrade pip", "pip install -r requirements.txt"]

[phases.build]
cmds = ["echo 'Build complete'"]

[start]
cmd = "gunicorn -w 4 -b 0.0.0.0:$PORT --timeout 120 --log-level info --access-logfile - --error-logfile - app:app"

[variables]
PYTHON_VERSION = "3.11"